# Site settings
title: Time & Pressure
tagline: # Gems from my journey in DevOps, AWS, Linux, Business Analysis and Life
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: # the subpath of your site, e.g. /blog/
url: "https://adamhettinger.github.io" # the base hostname & protocol for your site
logourl: # /assets/images/logo.png # Site logo
author: Adam Hettinger
author_thumbnail:  # Author avatar

excerpt_separator: <!--more-->

# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social:
    github: adamhettinger
    twitter:
    facebook:
    gplus:
    pinterest:

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: 

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key:

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 15

# Files/Folders to be excluded from generated _site folder
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
